version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=lux_shop
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    expose:
      - 3306

  backend:
    build:
      context: ../backend-lux-shop
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - URL_REACT=http://localhost
      - DB_DIALECT=mysql
      - NODE_ENV=development
      - DB_DATABASE_NAME=lux_shop
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - PORT=8080
    ports:
      - 8080:8080
    expose:
      - 8080

  nginx:
    image: nginx:1.25.2
    ports:
      - 80:80
    volumes:
      - ../frontend-lux-shop-admin/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

# docker compose -p lux-shop up -d
