const actionTypes = Object.freeze({
  CREATE_NEW_PRODUCT_SUCCESS: "CREATE_NEW_PRODUCT_SUCCESS",
  CREATE_NEW_PRODUCT_FALSE: "CREATE_NEW_PRODUCT_FALSE",
  CREATE_COLOR_TABLE_SUCCESS: "CREATE_COLOR_TABLE_SUCCESS",
  CREATE_COLOR_TABLE_FALSE: "CREATE_COLOR_TABLE_FALSE",
  FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FALSE: "FETCH_PRODUCT_FALSE",
  CREATE_NEW_COLOR_SUCCESS: "CREATE_NEW_COLOR_SUCCESS",
  CREATE_NEW_COLOR_FALSE: "CREATE_NEW_COLOR_FALSE",
});

export default actionTypes;
